init:
  - git config --global core.autocrlf false
version: '{build}'
environment:  
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      nodejs_version: "8"
  access_token:
    secure: gPLaCoISbGAJCbPE7vGAEkRMtiDH17XvyEzweZlp8pt6zjsOCTMZlmd1296tzgcz
  git_email:
    secure: dCEJcIf4jXWH0PrQcRaXuvvT8l7C5GwosxOsmi0c564=
# Start builds on tags only (GitHub and BitBucket)
# skip_non_tags: true
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
# Install scripts. (runs after repo cloning)
install:
  - copy C:\MinGW\bin\mingw32-make.exe C:\MinGW\bin\make.exe 
  - set PATH=%PATH%;C:\MinGW\bin
  # - ps: $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
  # - ps: [Environment]::SetEnvironmentVariable("Path", "$env:Path;c:\Users\Me\AppData\Roaming\npm\", "User")
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version

 
 
build_script:
  # install modules
  - npm install
  # run webpack with production flag
  - webpack -p
test: off
on_success:
  # - gh-pages deploy
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "$($env:git_email)"
  - git config --global user.name "codeyu"
  - git config --global core.autocrlf true
  - git clone -b gh-pages "https://github.com/codeyu/mini-mvvm.git" gh-pages
  - cd gh-pages
  - ps: if (-not $?) { throw "Cloning gh-pages failed" }
  - ps: Remove-Item * -Recurse
  - ps: Copy-Item ..\dist\* . -Recurse
  - git add --all .
  - git commit -m "update dist"
  - git push origin gh-pages